version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=blog_api
      - JWT_SECRET=change_me_in_prod
      - JWT_EXPIRES_IN=1h
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
